title: Data Science Resource Repository
author: Mustansir Udaipurwala
email: mhusain@mhusa.in
description: > # this means to ignore newlines until "baseurl:"
  A continously updated one-place for all data science resources I've been reading. These may help you too in your data science journeys.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
